apiVersion: v1
kind: Service
metadata:
  name: chatroom-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: app-instance
    app.kubernetes.io/name: app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  sessionAffinity: None
